version: '3'
services: 
  app:
    image: node:16-slim
    platform: linux/amd64
    volumes:
      - ./frontend/todoApp-vue3:/app
    working_dir: /app
    command: bash -c "npm update && npm run serve"
    ports:
      - 8080:8080
    restart: always


# ネットワークの情報
# networks:
#   myNetwork:

# ボリュームの情報
# volumes:
#   mySqlVolume:
#   wordpressVolume:
